spring.config.import=optional:file:.env.properties
chat.base-url=http://${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT}
indexing.base-url=http://${INDEXING_SERVICE_HOST}:${INDEXING_SERVICE_PORT}
data.base-url=http://${DATA_SERVICE_HOST}:${DATA_SERVICE_PORT}
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
CHAT_SERVICE_HOST=localhost
CHAT_SERVICE_PORT=5001
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
INDEXING_SERVICE_HOST=localhost
INDEXING_SERVICE_PORT=5000
DATA_SERVICE_HOST=localhost
DATA_SERVICE_PORT=5002
POSTGRES_HOST=postgres

