spring.config.import=optional:file:.env.properties
chat.base-url=http://${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT:80}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin


